[package]
name = "custom_site"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
dotenv = "0.15"
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.23"
time = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"

