[workspace]
members = [
    "crates/hacker_news",
    "crates/github",
    "crates/orchestrator",
    "crates/custom_site",
    # "crates/arxiv",
    # "crates/scheduler", # optional
]

resolver = "2"

# [profile.release]
# lto = true
# codegen-units = 1
