[workspace]
members = [
    "crates/common",
    "crates/hacker_news",
    "crates/github",
    "crates/orchestrator",
    "crates/arxiv",
    "crates/xai_search"
]

resolver = "2"

# [profile.release]
# lto = true
# codegen-units = 1
