[package]
name = "arxiv"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }
scraper = "0.23"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
